labs/MvcIdentityLab/MvcIdentityLab/Controllers/BSTUController.cs
using System.Web.Mvc;

namespace MvcIdentityLab.Controllers
{
    public class BSTUController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Config()
        {
            return View();
        }
    }
}

labs/MvcIdentityLab/MvcIdentityLab/Controllers/FIEController.cs
using System.Web.Mvc;

namespace MvcIdentityLab.Controllers
{
    public class FIEController : Controller
    {
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIE_TM()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIE_UR()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIE_UP()
        {
            return View();
        }
    }
}

labs/MvcIdentityLab/MvcIdentityLab/Controllers/FITController.cs
using System.Web.Mvc;

namespace MvcIdentityLab.Controllers
{
    public class FITController : Controller
    {
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIT_IS()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIT_PI()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FIT_ID()
        {
            return View();
        }
    }
}

labs/MvcIdentityLab/MvcIdentityLab/Controllers/FLTController.cs
using System.Web.Mvc;

namespace MvcIdentityLab.Controllers
{
    public class FLTController : Controller
    {
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FLT_LV()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FLT_LU()
        {
            return View();
        }

        [Authorize(Roles = "Employer")]
        public ActionResult FLT_LZ()
        {
            return View();
        }
    }
}

labs/MvcIdentityLab/MvcIdentityLab/Views/BSTU/Config.cshtml
@{
    ViewBag.Title = "BSTU/Config";
}

<h2>BSTU/Config</h2>
<h1>Доступ для пользователей с ролью Administrator</h1>

labs/MvcIdentityLab/MvcIdentityLab/Views/BSTU/Index.cshtml
@{
    ViewBag.Title = "BSTU/Index";
}

<h2>BSTU/Index</h2>
<div>
    @Html.ActionLink("Ссылка на FIT/Index", "Index", "FIT") <br />
    @Html.ActionLink("Ссылка на FLT/Index", "Index", "FLT") <br />
    @Html.ActionLink("Ссылка на FIE/Index", "Index", "FIE") <br />
    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Administrator"))
        {
            @Html.ActionLink("Ссылка на BSTU/Config", "Config")
        }
    }
</div>